### ISSUE TITLE
Appeler Max pour savoir pourquoi il n'y a que 600 dossier comportant des actions

### ISSUE THREAD

**Issue by qmoret** [dataforgoodfr/batch2_cresus#1]

**Comment by hippolytej** [comment]
La table action est remplie par un outil du CRM ("action") que très peu de conseillers utilisent actuellement. La plupart effectuent le suivi du dossier directement dans la zone de texte à leur disposition.

**Comment by yterme** [comment]
Sais-tu si la zone de texte est enregistrée quelque part ?

**Comment by hippolytej** [comment]
Elle est enregistrée, je ne sais pas encore dans quel champs en revanche, quoi qu'il en soit elle a été effacée à l'anonymisation.
