### ISSUE TITLE
Extraire de la base SQL les informations non formatées vers un csv

### ISSUE THREAD

**Issue by Iwontbecreative** [dataforgoodfr/batch2_cresus#3]
Objectif : Créer un fichier csv  qui peut ne pas être formaté (i.e duplicatas pour les lignes).
Rendu : Un lien wetransfer/google drive avec le fichier, ne pas mettre sur github les données (on ne veut pas qu'elles soient en libre accès). Envoyer un mail/message sur slack avec le lien wetransfer ou drive.

**Comment by qmoret** [comment]
Done !

**Comment by Iwontbecreative** [comment]
@qmoret Peux-tu ajouter le code du script sql que tu as utilisé au github pour qu'on puisse reproduire la démarche facilement en cas de besoin/actualisation du dataset ?

**Comment by qmoret** [comment]
Voilà qui est fait
