### ISSUE TITLE
Remplir le Readme 

### ISSUE THREAD

**Issue by martindaniel4** [dataforgoodfr/batch2_cresus#5]
Hello Thibault,

J'aimerais en savoir plus sur votre projet et savoir comment on peut vous aider ! Pouvez vous : 

- Remplir le Readme
- Ajouter les compétences que tu recherches pour ce projet (si c'est le cas). 

Thanks!

**Comment by Iwontbecreative** [comment]
Hello,

C'est fait, cela devrait être plus clair avec 566eace
