### ISSUE TITLE
Enlever les duplicatas causés par la table budget

### ISSUE THREAD

**Issue by qmoret** [dataforgoodfr/batch2_cresus#6]
Pour un id_dossier donné, il peut y avoir plusieurs types de budget : "réel", "déclaratif", "prévisionnel"... (correspondant à plusieurs lignes dans la table budget, donc dupliqués dans l'extract csv)
Il faut choisir un unique budget par id_dossier
-> Voir avec Max comment sont établis les différents types
-> Déterminer lequel / lesquels on retient

**Comment by Iwontbecreative** [comment]
Mon idee quand je bossais dessus (je vais reprendre) : le budget le plus récent est le meilleur. Il y a aussi différents types (réels vs provisionnels), l'alternative serait de prendre le réel quand possible et sinon le plus récent.

**Comment by Iwontbecreative** [comment]
Closing given 2285c9f
