### ISSUE TITLE
Déterminer comment aggréger les crédits

### ISSUE THREAD

**Issue by qmoret** [dataforgoodfr/batch2_cresus#7]
Un dossier possédant plusieurs crédits a autant de lignes dans l'extract.
Une solution serait de grouper par type de crédit en rajoutant les colonnes `mensualite_i`, `nb_mensualite_i`, et `solde_i` pour tous les types de crédits `i` (il y en a 5)
Il faudrait alors déterminer les opérations à effectuer pour grouper (additionner les mensualités ? moyenner le nombre de mensualités en pondérant ? etc)

**Comment by qmoret** [comment]
nb_mensualite est souvent à 0 ou à 1... A creuser

**Comment by qmoret** [comment]
Mais sinon il y a moyen de s'en sortir avec une requête de la sorte dans SQL :
`SELECT id_dossier, type_credit, sum(mensualite), avg(nb_mensualite), sum(solde)`
`FROM credits`
`WHERE mensualite <>0 OR nb_mensualite <> 0 OR solde <> 0`
`GROUP BY id_dossier, type_credit;`
Ce qui permet de faire passer de 26615 lignes à 9441
Seul problème on pert de l'info à la base, il serait du coup peut être bon de le faire dans python

**Comment by Iwontbecreative** [comment]
Gros problèmes aussi avec l'info sur les caractéristiques du crédit parfois contenue dans d'autres champs i.e description/entreprise.

**Comment by Iwontbecreative** [comment]
Closing given 2285c9f0
