### ISSUE TITLE
Demander à Max à quoi correspond la catégorie 'Aucune' dans le champ 'orientation

### ISSUE THREAD

**Issue by qmoret** [dataforgoodfr/batch2_cresus#8]
Aucune = pas encore d'orientation ou pas besoin d'accompagnement par Cresus ?

**Comment by hippolytej** [comment]
Aucune = soit information non renseignée (l'orientation n'est réellement utilisée par les conseillers que depuis 2016) soit pas encore orienté, rarement pas besoin d'orientation.
